# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sB0OLu7a7lWWkTIfb0yuC76H8QJoRbXf
"""

import json
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker

# 1. Ingest Data directly from your workspace
with open('annual_data.json', 'r') as f:
    data = json.load(f)

# Filter for the macro 2009-2026 timeline and sort chronologically
processed_data = [row for row in data if int(row['year']) >= 2009]
processed_data.sort(key=lambda row: int(row['year']))

years = [row['year'] for row in processed_data]
# Convert growth decimals to explicit percentages (e.g., 0.025 -> 2.5%)
gdp_growth = [row['gdp_growth_real'] * 100 for row in processed_data]

# 2. Establish Palette Theme Continuity (Matches annual.html and prior charts)
bg_color = '#0f172a'       # Deep Slate Canvas
card_bg = '#1e293b'        # Darker Card Containers
text_main = '#f8fafc'      # Bright text
text_muted = '#94a3b8'     # Slate gray text
accent_blue = '#38bdf8'    # Sky Blue for Positive Expansion Years
color_danger = '#ef4444'   # Coral Red for Negative Contraction Years (e.g., 2020)

# 3. Initialize Figure Workspace
fig, ax = plt.subplots(figsize=(12, 6.5))
fig.patch.set_facecolor(bg_color)
ax.set_facecolor(card_bg)

# Configure background subtle grid
ax.grid(color='#334155', linestyle='--', linewidth=0.5, alpha=0.3, zorder=0)

# 4. Plot Dynamic Growth Bars
# Assign color conditionally: blue if growth >= 0, red if growth < 0
bar_colors = [accent_blue if val >= 0 else color_danger for val in gdp_growth]

rects = ax.bar(years, gdp_growth, color=bar_colors, alpha=0.85, width=0.6, zorder=3)

# 5. Apply Axis Layout Formatting
ax.set_xticklabels(years, color=text_muted, rotation=45, fontsize=10.5)
ax.tick_params(colors=text_muted)

ax.set_title('Real GDP Headline Growth Rate (2009–2026)', color=text_main, fontsize=14, pad=20, weight='bold')
ax.set_ylabel('Annual Real Change (%)', color=text_muted, fontsize=11, labelpad=12)

# Custom percentage formatter for the Y-axis ticks
def percent_format(x, pos):
    if x == 0: return '0.0%'
    return f'+{x:.1f}%' if x > 0 else f'{x:.1f}%'
ax.get_yaxis().set_major_formatter(ticker.FuncFormatter(percent_format))

# Give slight breathing room at top and bottom of scales
ax.set_ylim(min(gdp_growth) - 1.0, max(gdp_growth) + 1.0)

# Remove harsh borders, keep slate bounds
for spine in ax.spines.values():
    spine.set_color('#334155')

# Draw a clean baseline at 0.0% to anchor the vertical bars
ax.axhline(0, color=text_muted, linewidth=1, linestyle='-', alpha=0.5, zorder=2)

# Tighten layout and render
plt.tight_layout()
plt.show()