# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sB0OLu7a7lWWkTIfb0yuC76H8QJoRbXf
"""

import json
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker

# 1. Ingest Data directly from your workspace
with open('annual_data.json', 'r') as f:
    data = json.load(f)

# Filter for the macro 2009-2026 timeline and sort chronologically
processed_data = [row for row in data if int(row['year']) >= 2009]
processed_data.sort(key=lambda row: int(row['year']))

years = [row['year'] for row in processed_data]
goods = [row['trade_goods'] for row in processed_data]
services = [row['trade_services'] for row in processed_data]
total = [row['trade_total'] for row in processed_data]

# 2. Establish Palette Theme Continuity (Matches annual.html styles)
bg_color = '#0f172a'       # Deep Slate Canvas
card_bg = '#1e293b'        # Darker Card Containers
text_main = '#f8fafc'      # Bright text
text_muted = '#94a3b8'     # Slate gray text
accent_blue = '#38bdf8'    # Sky Blue Total Net Vector
color_goods = '#ef4444'    # Coral/Rose Deficit
color_services = '#10b981' # Emerald Surplus

# 3. Initialize Figure Workspace
fig, ax = plt.subplots(figsize=(15, 8.5))
fig.patch.set_facecolor(bg_color)
ax.set_facecolor(card_bg)

# Configure background subtle grid
ax.grid(color='#334155', linestyle='--', linewidth=0.5, alpha=0.3, zorder=0)

# Build aligned x-axis configurations
x = np.arange(len(years))
width = 0.38

# 4. Plot Structural Elements
rects_goods = ax.bar(x - width/2, goods, width, label='Goods Balance (Deficit)', color=color_goods, alpha=0.85, zorder=3)
rects_services = ax.bar(x + width/2, services, width, label='Services Balance (Surplus)', color=color_services, alpha=0.85, zorder=3)
ax.plot(x, total, color=accent_blue, linewidth=3.5, marker='o', markersize=7, label='Total Net Trade Balance', zorder=4)

# 5. Inject Clean Data Labels Locked Dead-Center (Values only, zero clutter)
goods_labels = [f'{int(v):,}' for v in goods]
services_labels = [f'+{int(v):,}' for v in services]

ax.bar_label(rects_goods, labels=goods_labels, color=text_main, fontsize=8.5, label_type='center', weight='bold', rotation=90)
ax.bar_label(rects_services, labels=services_labels, color=text_main, fontsize=8.5, label_type='center', weight='bold', rotation=90)

# 6. Apply Axis Layout Formatting
ax.set_xticks(x)
ax.set_xticklabels(years, color=text_muted, rotation=45, fontsize=10.5)
ax.tick_params(colors=text_muted)

ax.set_title('Trade Balance Matrix Component Breakdown (2009–2026)', color=text_main, fontsize=15, pad=25, weight='bold')
ax.set_ylabel('Billions of Dollars (USD)', color=text_muted, fontsize=11, labelpad=12)

# Custom currency formatter for the primary left Y-axis ticks
def currency_format(x, pos):
    if x == 0: return '$0'
    return f'-${abs(int(x)):,}' if x < 0 else f'+${int(x):,}'
ax.get_yaxis().set_major_formatter(ticker.FuncFormatter(currency_format))

# Give breathing room on y-axis limits so text labels don't clip top/bottom
ax.set_ylim(min(goods) - 150, max(services) + 150)

# Remove harsh borders, keep slate bounds
for spine in ax.spines.values():
    spine.set_color('#334155')

# Draw clean baseline
ax.axhline(0, color=text_muted, linewidth=1, linestyle='-', alpha=0.5, zorder=2)

# 7. Format + Scale Legend up by 25% (fontsize set to 12.5) anchored in the safe lower-left zone
legend = ax.legend(facecolor=card_bg, edgecolor='#334155', loc='lower left', framealpha=1, borderpad=1.2, fontsize=12.5)
plt.setp(legend.get_texts(), color=text_main)

plt.tight_layout()
plt.show()